---
title: "Untitled"
format: html
editor: visual
---

# Libraries

```{r}
library(phyloseq)
library(qiime2R)
library(biomformat)
library(readr)
library(tidyverse)
library(ape)
library(Biostrings)
library(ggtree)
library(sva)
library(vegan)
library(ggExtra)
```

```{r}
source("~/Documents/ODSi/ODSiData/Functions/check_phyloseq.R")
source("~/Documents/ODSi/ODSiData/Functions/beta_pipe.R")
source("~/Documents/ODSi/ODSiData/Functions/parse_taxonomy.R")
source("~/Documents/ODSi/ODSiData/Functions/color_tips.R")
source("~/Documents/ODSi/ODSiData/Functions/filter_by_prevalence.R")
source("~/Documents/ODSi/ODSiData/Functions/plot_rarefaction_curves.R")
source("~/Documents/ODSi/ODSiData/Functions/debiasm.R")
source("~/Documents/ODSi/ODSiData/Functions/build_phyloseq.R")
source("~/Documents/ODSi/ODSiData/Functions/plot_beta_correction.R")
source("~/Documents/ODSi/ODSiData/Functions/suppress_all.R")
```

# Build phyloseq

Building from the Merging/full_cohort folder

```{r}
ps <- build_phyloseq("~/Documents/ODSi/ODSiData/Merging/full_cohort",
                     prefix   = "merged-",
                     meta_tsv = "~/Documents/ODSi/ODSiData/Merging/merged_metadata.tsv")
```

```{r}
check_phyloseq(ps)
```

# Visualizing

```{r}
genus_tree <- vizualize_collapse(ps, "Genus", show_labels = TRUE)
```

# Beta diversity

## How many taxa appear in only 1 study?

```{r}
singleton_ps <- filter_taxa(ps, function(x) sum(x > 0) ==1, prune = TRUE)
singleton_ps
```

## Filter by prevelance

```{r}
filtered_ps <- filter_by_prevalence(.05)
```

## Rarefaction

```{r}
plot_rarefaction_curves(filtered_ps, aggregate = "mean")
```

# Plotting before/after correction

```{r}
debiasm_ps <- debiasm_correct(filtered_ps)
```

```{r}
check_phyloseq(debiasm_ps)
```

## Full cohort

### Bray

```{r}
plot_beta_correction("!is.na(study)", 
                     ord_method = "bray",
                     phylo_obj = filtered_ps,
                     rare_depth = 900)
```

### Weighted Unifrac

```{r}
plot_beta_correction("!is.na(study)", 
                     ord_method = "wunifrac",
                     phylo_obj = filtered_ps,
                     rare_depth = 900)
```

## Exclude Ingham

```{r}

without_ingham <- plot_beta_correction("study != 'Ingham'", 
                     ord_method = "wunifrac",
                     phylo_obj = filtered_ps,
                     rare_depth = 900)


```

```{r}
print(without_ingham)
```

```{r}
baseline_without_ingham <- 
  plot_beta_correction("study != 'Ingham' & timepoint %in% c('conditioning', 'transplant')", 
                     ord_method = "wunifrac",
                     phylo_obj = filtered_ps,
                     rare_depth = 900)
```

```{r}
before_engraftment<- 
  plot_beta_correction("timepoint!='follow-up'", 
                     ord_method = "wunifrac",
                     phylo_obj = filtered_ps,
                     rare_depth = 900)
```

# Baseline

```{r}
baseline_ps <- subset_ps_func(filtered_ps,
                            "timepoint %in% c('pre-conditioning','conditioning', 'transplant') & disease != 'none'")
print(baseline_ps)
```

```{r}
baseline<- plot_beta_correction("!is.na(study)", 
                     ord_method = "wunifrac",
                     phylo_obj = baseline_ps,
                     rare_depth = 900)
```

```{r}
baseline <- plot_beta_correction("!is.na(study)", 
                     ord_method = "wunifrac",
                     phylo_obj = baseline_ps,
                     rare_depth = 900)
```
