---
title: "Preprocessing"
format: html
editor: visual
---

# Reference

-   Full citation: Bergeron, A., Chevret, S., Granata, A., Chevallier, P., Vincent, L., Huynh, A., Tabrizi, R., Labussiere-Wallet, H., Bernard, M., Chantepie, S., Bay, J.-O., Thiebaut-Bertrand, A., Thepot, S., Contentin, N., Fornecker, L.-M., Maillard, N., Risso, K., Berceanu, A., Blaise, D., Tour, R.P. de L., Chien, J.W., Coiteux, V., Socié, G., Investigators, A.S., 2017. Effect of Azithromycin on Airflow Decline–Free Survival After Allogeneic Hematopoietic Stem Cell Transplant: The ALLOZITHRO Randomized Clinical Trial. JAMA 318, 557–566. <https://doi.org/10.1001/jama.2017.9938>

-   Associated github: <https://gitlab.com/nivall/azimutfeces>

-   Bioproject: PRJNA902819

# Software Versions

Sra toolkit

```         
(sra-env) sophiehuebler@Sophies-MBP RawData % prefetch --version

prefetch : 3.2.1

(sra-env) sophiehuebler@Sophies-MBP RawData % fastq-dump --version

fastq-dump : 3.2.1
```

# Data Access

-   meta_samples.csv downloaded from bioproject

    -   (November 25, 2025)

-   meta_clinical.xlsx downloaded from github (data/metadata/azimut_md_feces.csv)

    -   (November 25, 2025)

-   sequences downloaded from bioproject

    -   (February 4, 2026)

# Reading Data

## Getting accessions

```         
arch -x86_64 zsh
source ~/miniconda3-x86_64/etc/profile.d/conda.sh
cd ~/Documents/ODSi/ODSiData/Allozithro2017/RawData
conda activate sra-env
prefetch --option-file run_accessions.txt
cat run_accessions.txt | while read srr; do fasterq-dump --split-files --progress "$srr"; done
conda deactivate
```

## Creating manifest

```         
../../create_manifest_script.sh
```

## Importing to qiime
