---
title: "Preprocessing Fujimoto 2024"
format: html
editor: visual
---

# Fujimoto (New)

-   V3-V4 region

# Reference

-   Full citation: Fujimoto, K., Hayashi, T., Yamamoto, M., Sato, N., Shimohigoshi, M., Miyaoka, D., Yokota, C., Watanabe, M., Hisaki, Y., Kamei, Y., Yokoyama, Y., Yabuno, T., Hirose, A., Nakamae, M., Nakamae, H., Uematsu, M., Sato, S., Yamaguchi, K., Furukawa, Y., Akeda, Y., Hino, M., Imoto, S., Uematsu, S., 2024. An enterococcal phage-derived enzyme suppresses graft-versus-host disease. Nature 632, 174–181. https://doi.org/10.1038/s41586-024-07667-8

-   Bioproject: [PRJNA1109929](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA1109929)

# Relevant Methods

-   The 16S rRNA V3–V4 region was PCR-amplified using specific primers (forward primer: 5′-ACACGACGCTCTTCCGATCTCCTACGGGNG GCWGCAG-3′, reverse primer: 5′-GACGTGTGCTCTTCCGATCTGACTA CHVGGGTATCTAATCC-3′, underline: overhang sequence for secondround PCR) over 20 cycles, and the PCR products were purified with Agencourt AMpure beads (Beckman Coulter) as described previously15. Then, the overhang and index sequences required for sequencing were added by a second round of PCR using NEBNext multiplex Oligos for Illumina (Dual Index Primers Set1, New England Biolabs) over eight cycles, and the products were purified with Agencourt AMpure beads. For each sample, equal amounts of each DNA amplicon library were mixed and sequenced on an MiSeq instrument (Illumina) using the MiSeq v3 Reagent kit and a 15% PhiX spike (Illumina). 16S rRNA gene analysis was performed using QIIME2 (v.2018.11; https://qiime2.org). In brief, raw sequence data were subjected to primer sequence trimming, quality filtering and paired-end read merging using the dada2 denoise-paired method (–p-trim-left-f 17 –p-trim-left-r 21–p-trunc-len-f 275 –p-trunc-len-r 215 –p-n-threads 16). Before taxonomic analysis, sequences of the 16S rRNA V3–V4 region were extracted from Greengenes 13_8 99% operational taxonomic units and our primer sequences using the q2-feature-classifier. Then, the Naive Bayes classifier was trained using the extracted Greengenes 13_8 reference sequences and Greengenes 13_8 99% operational taxonomic unit taxonomy. The taxonomic composition was visualized using a qiime taxa bar plot.
-   
-   

# Data Access

-   meta_samples.csv downloaded from bioproject

    -   (March 9, 2026)

-   fuji_meta_qiime.tsv generated in R Fujimoto2024/Metadata/Parsing_metadata.qmd

    -   (March 9, 2026)

-   meta_clinical.xlsx copied (by hand) from Supplementary Table 2

    -   (March 9, 2026)

# Fetch and Import
